version: '3.7'

services:
  database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psadmin -d kiosk"]
      interval: 5s
      timeout: 5s
      retries: 5

    container_name: kiosk-v2-database
    restart: always
    ports:
      - 5433:5432

    env_file:
      - ./dev-env/database.env

    image: postgres:17.6-trixie

    volumes:
      - ./database/data:/var/lib/postgresql/data

    networks:
     - kiosk-network

  backend:
    container_name: kiosk-v2-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: ./dev-env/backend.env

    ports:
      - 3001:8000
    depends_on:
      - database

    networks:
      - kiosk-network

    volumes:
      - ./backend/kioskCZN:/home/django-app/kioskCZN
      - ./logs:/home/django-app/kioskCZN/logs
      - ./kiosk_media:/home/django-app/kioskCZN/media
      - ./kioskContollerAppMigrations:/home/django-app/kioskCZN/kioskController/migrations

  # frontend:
  #   container_name: kiosk-v2-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: prod.dockerfile
  #   env_file: ./dev-env/frontend.env

  #   ports:
  #     - 3000:9000
  #   depends_on:
  #     - backend

  #   networks:
  #     - kiosk-network

  staff-scraper:
    container_name: kiosk-v2-staff-scraper
    build:
      context: ./staff-scraper
      dockerfile: prod.dockerfile
    env_file: ./dev-env/staff-scraper.env

    volumes:
      - ./logs:/home/staff-scraper/logs
      - ./phones_book_page:/home/staff-scraper/phones_book_page

    networks:
      - kiosk-network

  vacansy-scraper:
    container_name: kiosk-czn-vacansy-scraper
    build:
      context: ./vacansy-scraper
      dockerfile: prod.dockerfile
    env_file: ./dev-env/vacansy-scraper.env

    volumes:
      - ./logs:/home/vacansy-scraper/logs

    networks:
     - kiosk-network


networks:
  kiosk-network:
    driver: bridge